# Generated by Django 4.2.16 on 2024-11-03 01:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(max_length=255)),
                ('sellingPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None)),
                ('expiredate', models.DateField(verbose_name='Expiry Date')),
                ('isAvailable', models.BooleanField(default=True, verbose_name='Is Available')),
                ('materials', models.ManyToManyField(related_name='products', to='inventory.material')),
            ],
        ),
    ]
