# Generated by Django 4.2.16 on 2024-11-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_phone',
            field=models.CharField(max_length=100),
        ),
    ]
