# Generated by Django 4.2.16 on 2024-10-27 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('entity_id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('permission_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.BooleanField(default=False)),
                ('create', models.BooleanField(default=False)),
                ('edit', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
                ('full_access', models.BooleanField(default=False)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='db_diy.entity')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='db_diy.role')),
            ],
            options={
                'unique_together': {('role', 'entity')},
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('pwd', models.CharField(max_length=255)),
                ('fullname', models.CharField(max_length=255)),
                ('dob', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=255, unique=True)),
                ('tels', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='db_diy.rolepermission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='db_diy.users')),
            ],
            options={
                'unique_together': {('user', 'role_permission')},
            },
        ),
    ]
