# Generated by Django 4.2.16 on 2024-10-27 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_diy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='db_diy.role'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserRolePermission',
        ),
    ]
