# Generated by Django 4.2.16 on 2024-11-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_diy', '0002_users_role_delete_userrolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='mail',
            field=models.CharField(max_length=255),
        ),
    ]
